---
- name: grafana | set application facts
  ansible.builtin.set_fact:
    app_name: "grafana"
    app_image: "{{ grafana_docker_version }}"
    app_network: "{{ grafana_docker_network_name }}"
    app_base_path: "{{ grafana_docker_base_path }}"
    app_user: "{{ grafana_docker_user }}"
    app_uid: "{{ grafana_docker_uid }}"
    app_group: "{{ grafana_docker_group }}"
    app_gid: "{{ grafana_docker_gid }}"
    app_timezone: "{{ grafana_docker_timezone }}"
    app_environment_variables: "{{ grafana_docker_environment_variables }}"
    app_volumes: "{{ grafana_docker_volumes }}"
    app_labels: "{{ grafana_docker_labels }}"
    app_ports: "{{ grafana_docker_ports }}"

- name: "grafana | Ensure app folders exists"
  ansible.builtin.file:
    name: '{{ app_base_path }}/{{ app_name }}/{{ item }}'
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0770"
    state: directory
  with_items:
    - "data"
    - "data/dashboards"
    - "provisioning/dashboards"
    - "provisioning/datasources"
    - "provisioning/plugins"
    - "provisioning/notifiers"
    - "provisioning/alerting"

- name: grafana | get docker executable path
  ansible.builtin.command:
    cmd: "which docker"
  changed_when: false
  register: grafana_docker_executable_path

- name: "grafana | create docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ app_base_path }}/{{ app_name }}/docker-compose.yml"
    mode: "0640"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: grafana_restart

- name: "grafana | create dashboards provision"
  ansible.builtin.template:
    src: "dashboards.yml.j2"
    dest: "{{ app_base_path }}/{{ app_name }}/provisioning/dashboards/dashboards.yml"
    mode: "0640"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: grafana_restart

- name: "grafana | create datasources provision"
  ansible.builtin.template:
    src: "datasources.yml.j2"
    dest: "{{ app_base_path }}/{{ app_name }}/provisioning/datasources/datasources.yml"
    mode: "0640"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  notify: grafana_restart

- name: "grafana | Create systemd service"
  ansible.builtin.template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    mode: "0770"
    owner: "root"
    group: "root"
  notify:
    - grafana_systemd_reload
    - grafana_restart
